const Job = require("../models/Job");

const seedJobs = [
  {
    title: "Frontend Developer Intern",
    company: "Figma",
    type: "Internship",
    category: "IT",
    location: "Remote",
    stipend: "LKR 35,000/mo",
    deadline: "2026-04-10",
    posted: "2026-03-18",
    department: "Engineering",
    description:
      "Develop and maintain responsive frontend interfaces using React and TypeScript. Collaborate with design and backend teams.",
    skills: ["React", "TypeScript", "CSS"],
    experience: "Entry Level",
    workMode: "Remote",
    minEducation: "Bachelor's Degree (Ongoing)",
    academicYear: "Any Year",
    fieldOfStudy: "Computer Science",
    startDate: "2026-04-20",
    applicants: 45,
    status: "active",
    icon: "💻",
  },
  {
    title: "Data Analyst",
    company: "Dialog Axiata",
    type: "Full-time",
    category: "Finance",
    location: "Colombo",
    stipend: "LKR 120,000/mo",
    deadline: "2026-03-30",
    posted: "2026-03-14",
    department: "Analytics",
    description:
      "Analyze business data and create actionable insights. Build dashboards and reports using SQL and BI tools.",
    skills: ["SQL", "BI Tools", "Excel"],
    experience: "Entry Level",
    workMode: "On-site",
    minEducation: "Bachelor's Degree (Ongoing)",
    academicYear: "Final Year",
    fieldOfStudy: "Statistics",
    startDate: "2026-04-15",
    applicants: 28,
    status: "active",
    icon: "🗃️",
  },
  {
    title: "UI/UX Design Intern",
    company: "99X Technology",
    type: "Internship",
    category: "Design",
    location: "Hybrid",
    stipend: "LKR 25,000/mo",
    deadline: "2026-04-05",
    posted: "2026-03-17",
    department: "Design",
    description:
      "Create user-centered designs for web and mobile applications. Participate in design sprints and user testing.",
    skills: ["Figma", "UI Design", "Prototyping"],
    experience: "Entry Level",
    workMode: "Hybrid",
    minEducation: "Bachelor's Degree (Ongoing)",
    academicYear: "Any Year",
    fieldOfStudy: "Design",
    startDate: "2026-04-12",
    applicants: 19,
    status: "active",
    icon: "🎨",
  },
  {
    title: "Content Writer",
    company: "Roar Media",
    type: "Part-time",
    category: "Marketing",
    location: "Remote",
    stipend: "LKR 15,000/mo",
    deadline: "2026-03-28",
    posted: "2026-03-16",
    department: "Marketing",
    description:
      "Write engaging content for blogs, social media, and marketing campaigns. Optimize for SEO and brand voice.",
    skills: ["Writing", "SEO", "Social Media"],
    experience: "No Experience",
    workMode: "Remote",
    minEducation: "Bachelor's Degree (Ongoing)",
    academicYear: "Any Year",
    fieldOfStudy: "Journalism",
    startDate: "2026-04-08",
    applicants: 14,
    status: "expired",
    icon: "📝",
  },
  {
    title: "Machine Learning Intern",
    company: "WSO2",
    type: "Internship",
    category: "Engineering",
    location: "Colombo",
    stipend: "LKR 40,000/mo",
    deadline: "2026-04-15",
    posted: "2026-03-19",
    department: "Engineering",
    description:
      "Build and train machine learning models. Work with Python and TensorFlow on real-world datasets.",
    skills: ["Python", "TensorFlow", "ML"],
    experience: "Entry Level",
    workMode: "On-site",
    minEducation: "Bachelor's Degree (Ongoing)",
    academicYear: "Final Year",
    fieldOfStudy: "Computer Science",
    startDate: "2026-04-25",
    applicants: 12,
    status: "active",
    icon: "🤖",
  },
  {
    title: "Social Media Assistant",
    company: "Kaizer Media",
    type: "Part-time",
    category: "Marketing",
    location: "Remote",
    stipend: "LKR 12,000/mo",
    deadline: "2026-04-01",
    posted: "2026-03-15",
    department: "Marketing",
    description:
      "Manage social media accounts and create engaging posts. Monitor analytics and community engagement.",
    skills: ["Social Media", "Content Creation", "Analytics"],
    experience: "No Experience",
    workMode: "Remote",
    minEducation: "Bachelor's Degree (Ongoing)",
    academicYear: "Any Year",
    fieldOfStudy: "Marketing",
    startDate: "2026-04-05",
    applicants: 9,
    status: "closed",
    icon: "📣",
  },
];

async function seedJobsIfNeeded() {
  const count = await Job.countDocuments();

  if (count > 0) {
    return;
  }

  await Job.insertMany(seedJobs);
  console.log(`Seeded ${seedJobs.length} jobs`);
}

module.exports = seedJobsIfNeeded;